"""initial database migration

Revision ID: 0386e7b58dad
Revises: 
Create Date: 2020-03-16 15:18:28.578976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0386e7b58dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('input_db', sa.String(length=255), nullable=True),
    sa.Column('output_db', sa.String(length=255), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction')
    # ### end Alembic commands ###
